classroom_bookstore/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from main.views import show_main, add_book_entry_form, add_book_entry_ajax_form, show_json, show_xml, \
    show_xml_by_id, show_json_by_id, register, login_user, logout_user, edit_book, delete_book, book_list, \
    create_book_flutter

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('add-book', add_book_entry_form, name='add_book'),
    path('add-book-ajax', add_book_entry_ajax_form, name='add_book_ajax'),
    path('json/', show_json, name='show_json'),
    path('xml/', show_xml, name='show_xml'),
    path('book-list/', book_list, name='book_list'),
    path('json/<str:id>', show_json_by_id, name='show_json_by_id'),
    path('xml/<str:id>', show_xml_by_id, name='show_xml_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit/<uuid:id>', edit_book, name='edit_book'),
    path('delete/<uuid:id>', delete_book, name='delete_book'),
    path('create-flutter/', create_book_flutter, name='create_book_flutter'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        {% block meta %}
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        {% endblock meta %}
        <script src="https://cdn.tailwindcss.com"></script>
        <link rel="stylesheet" href="{% static 'css/global.css' %}" />
        <link href='https://fonts.googleapis.com/css?family=Plus Jakarta Sans' rel='stylesheet'>
    </head>
    
    <body>
        {% block content %} {% endblock content %}
        <script type="text/JavaScript" src="{% static 'js/global.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/dompurify@3.1.7/dist/purify.min.js"></script>
    </body>
</html>

templates/footer.html
<footer class="text-white py-4 shadow-lg fixed bottom-0 left-0 z-40 w-screen relative" style="background-color: #2f4a5e;">
    <p class="text-left px-4 py-4 items-center justify-between">&copy; 2024 Classroom Bookstore</p>
    <nav class="text-white py-4 shadow-lg fixed bottom-0 left-0 z-40 w-screen relative" style="background-color: #2f4a5e;">
        <div class="container mx-auto flex justify-between items-center">
            <div class="text-center flex-grow">
                <!-- Center-aligned content can go here if needed -->
            </div>
        </div>
    </nav>
</footer>

templates/navbar.html
<nav class="bg-light-indigo shadow-lg fixed top-0 left-0 z-40 w-screen relative navbar">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex items-center justify-between h-16">
        <div class="flex items-center">
          <h1 class="text-2xl font-bold text-center text-gray-100 animate-pulse">Classroom Bookstore</h1>
        </div>
        <div class="hidden md:flex items-center">
          {% if user.is_authenticated %}
          <div class="categories-buttons text-white flex flex-wrap justify-center items-center space-x-4 fixed top-0 left-0 z-40 relative">
              <div class="cursor-pointer space-x-3">
                <a id="home-button" class="text-white font-bold py-2 px-4 rounded transition duration-300">
                  Home
                </a>
                <a class="dropdownButton text-white font-bold py-2 px-4 rounded transition duration-300">
                  Book Categories
                  <svg class="w-4 h-4 inline-block ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path>
                  </svg>
                </a>
                <div class="dropdownMenu hidden absolute left-0 w-full bg-light-indigo rounded mt-2 shadow-lg border-gray-300">
                  <a href="#" onclick="filterSelection('all')" class="block px-4 py-2 text-white hover:bg-gray-200">Show All</a>
                  <a href="#" onclick="filterSelection('Light Novel / Manga')"class="block px-4 py-2 text-white hover:bg-gray-200">Light Novel / Manga</a>
                  <a href="#" onclick="filterSelection('Mystery / Thriller')" class="block px-4 py-2 text-white hover:bg-gray-200">Mystery / Thriller</a>
                  <a href="#" onclick="filterSelection('Self-Help')" class="block px-4 py-2 text-white hover:bg-gray-200">Self-Help</a>
                  <a href="#" onclick="filterSelection('Philosophy')" class="block px-4 py-2 text-white hover:bg-gray-200">Philosophy</a>
                  <a href="#" onclick="filterSelection('Biography')" class="block px-4 py-2 text-white hover:bg-gray-200">Biography</a>
                  <a href="#" onclick="filterSelection('Junior-Kids')" class="block px-4 py-2 text-white hover:bg-gray-200">Junior-Kids</a>
                </div>
                <a id="cart" class="text-white font-bold py-2 px-4 rounded transition duration-300">
                  Cart
                  <svg class="w-4 h-4 inline-block ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-1.4 5h11.2L17 13M5.4 5H19M5.4 5L4 3M17 13l1.4 5M9 21h6"></path>
                  </svg>
                </a>
                <a class="dropdownButton text-white font-bold py-2 px-4 rounded transition duration-300">
                  About Us
                  <svg class="w-4 h-4 inline-block ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path>
                  </svg>
                </a>
                <div class="dropdownMenu hidden absolute left-0 w-full bg-light-indigo rounded mt-2 shadow-lg border-gray-300">
                  <a href="#" class="block px-4 py-2 text-white hover:bg-gray-200">About Us</a>
                  <a href="#" class="block px-4 py-2 text-white hover:bg-gray-200">Contact Us</a>
                  <a href="#" class="block px-4 py-2 text-white hover:bg-gray-200">FAQ</a>
                  <a href="#" class="block px-4 py-2 text-white hover:bg-gray-200">Terms and Conditions</a>
                  <a href="#" class="block px-4 py-2 text-white hover:bg-gray-200">Privacy Policy</a>
                </div>
              </div>
            <p></p>
          </div>
          <div class="flex items-center">
            <span class="text-gray-200 mr-4 animate-bounce">Welcome, {{ user.username }}</span>
            <a href="{% url 'main:logout' %}" class="text-center bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded transition duration-300">
              Logout
            </a>
          </div>
          {% else %}
            <a href="{% url 'main:login' %}" class="text-center bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded transition duration-300 mr-2">
              Login
            </a>
            <a href="{% url 'main:register' %}" class="text-center bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded transition duration-300">
              Register
            </a>
          {% endif %}
        </div>
        <div class="md:hidden flex items-center">
          <button class="mobile-menu-button">
            <svg class="w-6 h-6 text-white" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor">
              <path d="M4 6h16M4 12h16M4 18h16"></path>
            </svg>
          </button>
        </div>
      </div>
    </div>
    <!-- Mobile menu -->
    <div class="mobile-menu hidden md:hidden  px-4 w-full md:max-w-full">
      <div class="pt-2 pb-3 space-y-1 mx-auto">
        {% if user.is_authenticated %}
          <div class="relative">
            <button id="home-button" class="w-full text-left bg-light-indigo text-white font-bold py-2 px-4 rounded transition duration-300">
                Home
            </button>
            <button class="dropdownButton w-full text-left bg-light-indigo text-white font-bold py-2 px-4 rounded transition duration-300">
              Book Categories
              <svg class="w-4 h-4 inline-block ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path>
              </svg>
            </button>
            <div class="dropdownMenu hidden absolute left-0 w-full bg-light-indigo rounded mt-2 shadow-lg border-gray-300">
              <a href="#" onclick="filterSelection('all')" class="block px-4 py-2 text-white hover:bg-gray-200">Show All</a>
              <a href="#" onclick="filterSelection('Light Novel / Manga')" class="block px-4 py-2 text-white hover:bg-gray-200">Light Novel / Manga</a>
              <a href="#" onclick="filterSelection('Mystery / Thriller')" class="block px-4 py-2 text-white hover:bg-gray-200">Mystery / Thriller</a>
              <a href="#" onclick="filterSelection('Self-Help')" class="block px-4 py-2 text-white hover:bg-gray-200">Self-Help</a>
              <a href="#" onclick="filterSelection('Philosophy')" class="block px-4 py-2 text-white hover:bg-gray-200">Philosophy</a>
              <a href="#" onclick="filterSelection('Biography')" class="block px-4 py-2 text-white hover:bg-gray-200">Biography</a>
              <a href="#" onclick="filterSelection('Junior-Kids')" class="block px-4 py-2 text-white hover:bg-gray-200">Junior-Kids</a>
            </div>
            <button id="cart" class="w-full text-left bg-light-indigo-600 text-white font-bold py-2 px-4 rounded transition duration-300 ">
              Carts
              <svg class="w-4 h-4 inline-block ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-1.4 5h11.2L17 13M5.4 5H19M5.4 5L4 3M17 13l1.4 5M9 21h6"></path>
              </svg>
            </button>
            <button class="dropdownButton w-full text-left bg-light-indigo-600 text-white font-bold py-2 px-4 rounded transition duration-300">
              About Us
              <svg class="w-4 h-4 inline-block ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path>
              </svg>
            </button>
            <div class="dropdownMenu hidden absolute left-0 w-full bg-light-indigo rounded mt-2 shadow-lg border-gray-300">
              <a href="#" class="block px-4 py-2 text-white hover:bg-gray-200">About Us</a>
              <a href="#" class="block px-4 py-2 text-white hover:bg-gray-200">Contact Us</a>
              <a href="#" class="block px-4 py-2 text-white hover:bg-gray-200">FAQ</a>
              <a href="#" class="block px-4 py-2 text-white hover:bg-gray-200">Terms and Conditions</a>
              <a href="#" class="block px-4 py-2 text-white hover:bg-gray-200">Privacy Policy</a>
            </div>
          <span class="block text-gray-200 px-4 py-2 welcome-text animate-bounce">
            Welcome, {{ user.username }}</span>
          <a href="{% url 'main:logout' %}" class="block text-center bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded transition duration-300">
            Logout
          </a>
        {% else %}
          <a href="{% url 'main:login' %}" class="block text-center bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded transition duration-300 mb-2">
            Login
          </a>
          <a href="{% url 'main:register' %}" class="block text-center bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded transition duration-300">
            Register
          </a>
        {% endif %}
      </div>
    </div>
</nav>
<hr>