classroom_bookstore/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from main.views import show_main, add_book_entry_form, add_book_entry_ajax_form, show_json, show_xml, \
    show_xml_by_id, show_json_by_id, register, login_user, logout_user, edit_book, delete_book, book_list, \
    create_book_flutter

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('add-book', add_book_entry_form, name='add_book'),
    path('add-book-ajax', add_book_entry_ajax_form, name='add_book_ajax'),
    path('json/', show_json, name='show_json'),
    path('xml/', show_xml, name='show_xml'),
    path('book-list/', book_list, name='book_list'),
    path('json/<str:id>', show_json_by_id, name='show_json_by_id'),
    path('xml/<str:id>', show_xml_by_id, name='show_xml_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit/<uuid:id>', edit_book, name='edit_book'),
    path('delete/<uuid:id>', delete_book, name='delete_book'),
    path('create-flutter/', create_book_flutter, name='create_book_flutter'),
]

main/forms.py
from django import forms
from django.forms import ModelForm
from main.models import BookEntry # import the BookEntry model from models.py\
from django.utils.html import strip_tags

class BookEntryForm(ModelForm):
    class Meta:
        model = BookEntry

        fields = [ # list of fields to be included in the form
            'name', 'price', 'description',
            'quantity', 'category', 'isbn_13', 'isbn_10', 'published_date', 
            'pages', 'language', 'weight',
            'author', 'publisher', 'image'
        ] # 'time_added' field is excluded as it is automatically generated
        
        widgets = { # dictionary of widgets to customize the form fields
            'published_date': forms.DateInput(attrs={'type': 'date'}),
            'image': forms.ClearableFileInput(attrs={'accept': 'image/*'}),
        } # customised details: published_date, review_list, image -> widgets 

        labels = { # dictionary of labels to customize the field labels
            'name': 'Book Title',
            'isbn_13': 'ISBN-13',
            'isbn_10': 'ISBN-10',
            'rating_star': 'Rating (0.0 - 5.0)',
        } # labels to be displayed in the form
        
        help_texts = { # dictionary of help texts to provide additional information
            'isbn_13': 'Enter the 13-digit ISBN number.',
            'isbn_10': 'Enter the 10-digit ISBN number.',
            'image': 'Upload an image of the book cover (.jpg, .jpeg, .png).',
        } # help texts to be displayed in the form

    # NOTE: Custom validation methods

    # Custom validation for rating star
    def clean_rating_star(self):
        rating_star = self.cleaned_data.get('rating_star')
        if rating_star is not None and (rating_star < 0.0 or rating_star > 5.0):
            raise forms.ValidationError('Rating must be between 0.0 and 5.0.')
        return rating_star

    # Custom validation for review list
    def clean_review_list(self):
        review_list = self.cleaned_data.get('review_list')
        if not isinstance(review_list, dict):
            raise forms.ValidationError('Review list must be a valid JSON object.')
        return review_list

    def clean_name(self):
        name = self.cleaned_data.get('name')
        return strip_tags(name)
    
    def clean_description(self):
        description = self.cleaned_data.get('description')
        return strip_tags(description)
    
    def clean_author(self):
        author = self.cleaned_data.get('author')
        return strip_tags(author)
    
    def clean_publisher(self):
        publisher = self.cleaned_data.get('publisher')
        return strip_tags(publisher)
    
    def clean_language(self):
        language = self.cleaned_data.get('language')
        return strip_tags(language)
    
    def clean_category(self):
        category = self.cleaned_data.get('category')
        return strip_tags(category)
    
    def clean_isbn_13(self):
        isbn_13 = self.cleaned_data.get('isbn_13')
        return strip_tags(isbn_13)
    
    def clean_isbn_10(self):
        isbn_10 = self.cleaned_data.get('isbn_10')
        return strip_tags(isbn_10)

main/views.py
import datetime, json
from main.models import BookEntry
from main.forms import BookEntryForm
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core import serializers
from django.contrib import messages
from django.shortcuts import render, redirect
from django.utils.html import strip_tags
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required(login_url='main:login')
def show_main(request):
    # data_books = []
    # data_books = [ # Dummy products that can't be edited or deleted
    #     BookEntry(name='Classroom of the Elite Year 2, Volume 1', price=235000, description='Classroom of The Elite Year 2, Volume 1 is a light novel written by Syougo Kinugasa and illustrated by Shunsaku Tomose. This light novel is the sequel of Classroom of The Elite Year 1, Volume 1. The story continues with the main character, Kiyotaka Ayanokouji, and his friends in the second year of their high school life. The story is set in the Advanced Nurturing High School, where students are divided into four classes based on their academic performance. The story follows the students as they navigate the challenges of high school life and strive to achieve their goals. The light novel is filled with suspense, drama, and mystery, making it a must-read for fans of the genre.',
    #               quantity=1, category='Light Novel / Manga', isbn_13='9781638581826', isbn_10='1638581827', published_date='2022-07-19', pages=480, language='English', weight=0.38, publisher='Airship', rating_star=0.0, rating_count=0, author='Syougo Kinugasa', time_added='2024-09-05 22:19:00', review_list={}, image=''),
    #     BookEntry(name='Classroom of the Elite Year 2, Volume 2', price=235000, description='Classroom of The Elite Year 2, Volume 2 is the continuation of the thrilling light novel series written by Syougo Kinugasa and illustrated by Shunsaku Tomose. In this volume, the story delves deeper into the complex dynamics of the Advanced Nurturing High School, where students are constantly tested both academically and socially. Kiyotaka Ayanokouji and his classmates face new challenges and adversaries as they navigate their second year. With unexpected twists and intense character development, this volume keeps readers on the edge of their seats. The intricate plot and suspenseful narrative make it a compelling read for fans of the series.',
    #               quantity=1, category='Light Novel / Manga', isbn_13='9781638583370', isbn_10='1638583377', published_date='2022-08-30', pages=488, language='English', weight=0.38, publisher='Airship', rating_star=0.0, rating_count=0, author='Syougo Kinugasa', time_added='2024-09-10 19:54:00', review_list={}, image=''),
    #     BookEntry(name='Classroom of the Elite Year 2, Volume 3', price=245000, description='Classroom of The Elite Year 2, Volume 3 continues the captivating journey of Kiyotaka Ayanokouji and his classmates at the Advanced Nurturing High School. Written by Syougo Kinugasa and illustrated by Shunsaku Tomose, this volume explores the deeper intricacies of the school\'s competitive environment. As the students face new trials and tribulations, alliances are tested and secrets are revealed. The stakes are higher than ever, and the characters must navigate through a web of deception and strategy to come out on top. This volume is packed with suspense, drama, and unexpected twists that will keep readers eagerly turning the pages.',
    #               quantity=1, category='Light Novel / Manga', isbn_13='9781638586425', isbn_10='1638583385', published_date='2022-12-15', pages=516, language='English', weight=0.40, publisher='Airship', rating_star=0.0, rating_count=0, author='Syougo Kinugasa', time_added='2024-09-10 20:00:00', review_list={}, image=''),
    #     BookEntry(name='Classroom of the Elite Year 2, Volume 4', price=245000, description='Classroom of The Elite Year 2, Volume 4 is the latest installment in the popular light novel series by Syougo Kinugasa and Shunsaku Tomose. In this volume, Kiyotaka Ayanokouji and his classmates face new challenges and obstacles as they navigate the competitive world of the Advanced Nurturing High School. With the stakes higher than ever, the students must rely on their wits and skills to outsmart their rivals and achieve their goals. Packed with suspense, intrigue, and unexpected twists, this volume is a must-read for fans of the series.',
    #               quantity=1, category='Light Novel / Manga', isbn_13='9781638588177', isbn_10='1638588171', published_date='2023-03-21', pages=512, language='English', weight=0.40, publisher='Airship', rating_star=0.0, rating_count=0, author='Syougo Kinugasa', time_added='2024-09-10 20:05:00', review_list={}, image=''),
    #     BookEntry(name='And Then There Were None', price=125000, description='And Then There Were None is a mystery novel by Agatha Christie, widely considered her masterpiece and described by her as the most difficult of her books to write. It was first published in the United Kingdom by the Collins Crime Club on 6 November 1939, as Ten Little N',
    #               quantity=1, category='Mystery / Thriller', isbn_13='9780062073488', isbn_10='0062073486', published_date='1939-11-06', pages=272, language='English', weight=0.25, publisher='HarperCollins', rating_star=0.0, rating_count=0, author='Agatha Christie', time_added='2024-09-10 20:10:00', review_list={}, image=''),
    #     BookEntry(name='The Daily Laws: 366 Meditations on Power, Seduction, Mastery, Strategy, and Human Nature', price=190000, description='The Daily Laws: 366 Meditations on Power, Seduction, Mastery, Strategy, and Human Nature is a book by Robert Greene, the author of The 48 Laws of Power, The Art of Seduction, The 33 Strategies of War, The 50th Law, and Mastery. The Daily Laws is a collection of 366 meditations, one for each day of the year, based on the timeless wisdom of Greene\'s previous works. Each meditation offers insights and strategies for navigating the complexities of power, seduction, mastery, strategy, and human nature. Whether you are seeking personal growth, professional success, or a deeper understanding of the world, The Daily Laws provides a daily dose of wisdom and inspiration to guide you on your journey.',
    #               quantity=1, category='Self-Help', isbn_13='9780593299234', isbn_10='059329923X', published_date='2023-09-05', pages=432, language='English', weight=0.50, publisher='Penguin Books', rating_star=0.0, rating_count=0, author='Robert Greene', time_added='2024-09-10 20:15:00', review_list={}, image=''),
    #     BookEntry(name='The Art of War', price=160000, description='The Art of War is an ancient Chinese military treatise attributed to Sun Tzu, a military strategist, and philosopher. The text is composed of 13 chapters, each focusing on different aspects of warfare and strategy. The Art of War has been widely studied and applied in various fields beyond military strategy, including business, politics, and sports. Its timeless wisdom and practical insights continue to be relevant in the modern world, making it a classic work on strategy and leadership.',
    #               quantity=1, category='Philosophy', isbn_13='9780141023816', isbn_10='0141023813', published_date='2005-11-01', pages=112, language='English', weight=0.08, publisher='Penguin Books', rating_star=0.0, rating_count=0, author='Sun Tzu', time_added='2024-09-10 20:20:00', review_list={}, image=''),
    #     BookEntry(name='The 48 Laws of Power', price=230000, description='The 48 Laws of Power is a practical guide to understanding power dynamics and mastering the art of persuasion. Written by Robert Greene, the book explores the timeless principles of power and influence that have shaped history and continue to impact the world today. Drawing on historical examples and psychological insights, Greene offers a comprehensive framework for navigating the complexities of power in various contexts. Whether you are a leader, entrepreneur, or student of human nature, The 48 Laws of Power provides valuable lessons and strategies for achieving your goals and influencing others.',
    #               quantity=1, category='Self-Help', isbn_13='9780140280197', isbn_10='0140280197', published_date='2000-09-01', pages=452, language='English', weight=0.45, publisher='Penguin Books', rating_star=0.0, rating_count=0, author='Robert Greene', time_added='2024-09-10 20:25:00', review_list={}, image=''),
    # ]
    # new_books = BookEntry.objects.all().order_by('-time_added').filter(user=request.user)
    # data_books = list(new_books) + data_books
    # categories = set([book.category for book in data_books])

    # for book in data_books:
    #     book.image = book.image_url()

    context = {
        'name': request.user.username,
        'class': 'PBP A Gasal 2024/2025',
        'npm': '2306211231',
        # 'data_books': data_books,
        # 'categories' : categories,
        'last_login': request.COOKIES.get('last_login'),
    }

    return render(request, "main.html", context)

def add_book_entry_form(request):
    form = BookEntryForm(request.POST or None, request.FILES or None)

    if form.is_valid() and request.method == 'POST':
        book_entry = form.save(commit=False)
        book_entry.user = request.user
        book_entry.save()
        return redirect('main:show_main')

    context = {'form': form}
    return render(request, 'add_book.html', context)

@csrf_exempt
@require_POST
def add_book_entry_ajax_form(request):
    if not request.user.is_authenticated:
        return HttpResponse(b"UNAUTHORIZED", status=401)
    
    user = request.user

main/templates/add_book.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block content %}
{% include 'navbar.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Classroom Bookstore: Add Book</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/global.css' %}">
</head>
<body>
<div class="flex flex-col min-h-screen bg-cyan-50">
    <div class="container mx-auto px-4 py-8 mt-16 max-w-xl">
        <h1 class="text-3xl font-bold text-center mb-8 text-black">Add Book Entry</h1>
            
            <div class="bg-gray-50 rounded-lg p-6 form-style">
                <form method="POST" class="space-y-6">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="flex flex-col">
                            <label for="{{ field.id_for_label }}" class="mb-2 font-semibold text-gray-700 plus-jakarta-sans">
                                {{ field.label }}
                            </label>
                            <div class="w-full plus-jakarta-sans">
                                {{ field }}
                            </div>
                            {% if field.help_text %}
                                <p class="mt-1 text-sm text-gray-500 plus-jakarta-sans">{{ field.help_text }}</p>
                            {% endif %}
                            {% for error in field.errors %}
                                <p class="mt-1 text-sm text-red-600">{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endfor %}
                    <div class="flex justify-center mt-6">
                        <button type="submit" class="bg-light-indigo text-white font-semibold px-6 py-3 rounded-lg hover:bg-gray-500 transition duration-300 ease-in-out w-full">
                            Add Book Entry
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>
</html>
{% endblock %}

main/templates/book_cards.html
{% load static %}
{% for book in books %}

<div class="book-cards border border-gray-300 rounded-lg shadow-md p-4 flex flex-col items-center justify-start bg-light-indigo {{ book.category|slugify }}">
    <div class="book-image max-w-xs h-auto rounded-lg flex justify-center items-center">
        <img src="{{ book.image.url }}" alt="{{ book.name }}">
    </div>
    <h2 class="font-bold text-lg text-greencs-light mt-4 plus-jakarta-sans" id="book-title">{{ book.name }}</h2>
    <div class="book-info w-full text-justify text-gray-600 mt-2">
        <p id="price-tag" class="font-bold"><strong>Price:</strong> Rp{{ book.price }},-</p>
        <p class="short-descr">{{ book.description|slice:":150" }}<span class="full-descr hidden">{{ book.description|slice:"150:" }}</span>
        <a href="javascript:void(0);" class="show-more text-blue-500" onclick="toggleDescription(this)">Show More</a></p>
        <p><strong>Category:</strong> {{ book.category }}</p>
        <p><strong>Author:</strong> {{ book.author }}</p>
        <p><strong>Published Date:</strong> {{ book.published_date }}</p>
        <p><strong>ISBN (13 digit):</strong> {{ book.isbn_13 }}</p>
        <p><strong>Availability Stock: {{ book.quantity }}</strong></p>
        <p><strong><img class="rating-star inline-block" src="{% static 'image/properties/rating-star.png' %}" alt="Rating Star">Rating:</strong> {{ book.rating_star }} / 5.0</p>

        <!-- Additional Attributes -->
        <span class="more-attributes hidden">
            <p><strong>ISBN (10 digit):</strong> {{ book.isbn_10 }}</p>
            <p><strong>Publisher:</strong> {{ book.publisher }}</p>
            <p><strong>Pages:</strong> {{ book.pages }}</p>
            <p><strong>Language:</strong> {{ book.language }}</p>
            <p><strong>Weight:</strong> {{ book.weight }} grams</p>
        </span>
        <a href="javascript:void(0);" class="show-more" onclick="toggleAttributes(this)">Show More</a>
        <br><br>

        <!-- Conditional Button -->
        {% if book.is_in_stock %}
            <button class="buy-button">Buy Now</button>
            <button class="add-to-cart-button">
                Add to Cart
                <svg class="w-4 h-4 inline-block ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-1.4 5h11.2L17 13M5.4 5H19M5.4 5L4 3M17 13l1.4 5M9 21h6"></path>
                </svg>
            </button>
        {% else %}
            <button class="remind-button">Remind Me</button>
        {% endif %}

        <!-- Options: Edit and delete book entry: -->
        <div class="book-options">
            <a href="{% url 'main:edit_book' book.pk %}" id="edit-book-link">
                <button id="edit-book-button">Edit Book Entry</button>
            </a>
            <a href="{% url 'main:delete_book' book.pk %}" id="delete-book-link">
                <button id="delete-book-button">Delete Book Entry</button>
            </a>
        </div>
    <hr class="gray-hr animate-shine">
    </div>
</div>

{% endfor %}

main/templates/edit_book.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block content %}
{% include 'navbar.html' %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Classroom Bookstore: Edit Book</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/global.css' %}">
</head>
<body>
<div class="flex flex-col min-h-screen bg-cyan-50">
    <div class="container mx-auto px-4 py-8 mt-16 max-w-xl">
        <h1 class="text-3xl font-bold text-center mb-8 text-black">Edit Book Entry</h1>
            
            <div class="bg-gray-50 rounded-lg p-6 form-style">
                <form method="POST" class="space-y-6">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="flex flex-col">
                            <label for="{{ field.id_for_label }}" class="mb-2 font-semibold text-gray-700 plus-jakarta-sans">
                                {{ field.label }}
                            </label>
                            <div class="w-full plus-jakarta-sans">
                                {{ field }}
                            </div>
                            {% if field.help_text %}
                                <p class="mt-1 text-sm text-gray-500 plus-jakarta-sans">{{ field.help_text }}</p>
                            {% endif %}
                            {% for error in field.errors %}
                                <p class="mt-1 text-sm text-red-600">{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endfor %}
                    <div class="flex justify-center mt-6">
                        <button type="submit" class="bg-light-indigo text-white font-semibold px-6 py-3 rounded-lg hover:bg-gray-500 transition duration-300 ease-in-out w-full">
                            Edit Book Entry
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>
</html>
{% endblock %}

main/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block content %}
{% include 'navbar.html' %}
<html lang="en">
<head>
    {% block meta %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login to Classroom Bookstore</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/global.css' %}">
    {% endblock meta %}
</head>
<body>
    <div class="min-h-screen flex items-center justify-center w-screen bg-gray-100 py-12 px-4 sm:px-6 lg:px-8">
        <div class="max-w-md w-full space-y-8">
          <div>
            <h2 class="mt-6 text-center text-black text-3xl font-extrabold text-gray-900">
              Login to your account
            </h2>
          </div>
          <form class="mt-8 space-y-6" method="POST" action="">
            {% csrf_token %}
            <input type="hidden" name="remember" value="true">
            <div class="rounded-md shadow-sm -space-y-px">
              <div>
                <label for="username" class="sr-only">Username</label>
                <input id="username" name="username" type="text" required class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" placeholder="Username">
              </div>
              <div>
                <label for="password" class="sr-only">Password</label>
                <input id="password" name="password" type="password" required class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" placeholder="Password">
              </div>
            </div>
      
            <div>
              <button type="submit" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                Sign in
              </button>
            </div>
          </form>
      
          {% if messages %}
          <div class="mt-4">
            {% for message in messages %}
            {% if message.tags == "success" %}
                  <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative" role="alert">
                      <span class="block sm:inline">{{ message }}</span>
                  </div>
              {% elif message.tags == "error" %}
                  <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
                      <span class="block sm:inline">{{ message }}</span>
                  </div>
              {% else %}
                  <div class="bg-blue-100 border border-blue-400 text-blue-700 px-4 py-3 rounded relative" role="alert">
                      <span class="block sm:inline">{{ message }}</span>
                  </div>
              {% endif %}
            {% endfor %}
          </div>
          {% endif %}
      
          <div class="text-center mt-4">
            <p class="text-sm text-black">
              Don't have an account yet?
              <a href="{% url 'main:register' %}" class="font-medium text-indigo-200 hover:text-indigo-300">
                Register Now
              </a>
            </p>
          </div>
        </div>
      </div>
</body>
{% endblock content %}
</html>

main/templates/register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block content %}
{% include 'navbar.html' %}
<html lang="en">
    <head>
    {% block meta %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register Form to Classroom Bookstore</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/global.css' %}">
    {% endblock meta %}
</head>
<body>
    <div class="min-h-screen flex items-center justify-center bg-gray-100 py-12 px-4 sm:px-6 lg:px-8">
        <div class="max-w-md w-full space-y-8 form-style">
          <div>
            <h2 class="mt-6 text-center text-3xl font-extrabold text-black">
              Create your account
            </h2>
          </div>
          <form class="mt-8 space-y-6" method="POST">
            {% csrf_token %}
            <input type="hidden" name="remember" value="true">
            <div class="rounded-md shadow-sm -space-y-px">
              {% for field in form %}
                <div class="{% if not forloop.first %}mt-4{% endif %}">
                  <label for="{{ field.id_for_label }}" class="mb-2 font-semibold text-black">
                    {{ field.label }}
                  </label>
                  <div class="relative">
                    {{ field }}
                    <div class="absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
                      {% if field.errors %}
                        <svg class="h-5 w-5 text-red-500" fill="currentColor" viewBox="0 0 20 20">
                          <path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7 4a1 1 0 11-2 0 1 1 0 012 0zm-1-9a1 1 0 00-1 1v4a1 1 0 102 0V6a1 1 0 00-1-1z" clip-rule="evenodd" />
                        </svg>
                      {% endif %}
                    </div>
                  </div>
                  {% if field.errors %}
                    {% for error in field.errors %}
                      <p class="mt-1 text-sm text-red-600">{{ error }}</p>
                    {% endfor %}
                  {% endif %}
                </div>
              {% endfor %}
            </div>
      
            <div>
              <button type="submit" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                Register
              </button>
            </div>
          </form>
      
          {% if messages %}
          <div class="mt-4">
            {% for message in messages %}
            <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
              <span class="block sm:inline">{{ message }}</span>
            </div>
            {% endfor %}
          </div>
          {% endif %}
      
          <div class="text-center mt-4">
            <p class="text-sm text-black">
              Already have an account?
              <a href="{% url 'main:login' %}" class="font-medium text-indigo-200 hover:text-indigo-300">
                Login here
              </a>
            </p>
          </div>
        </div>
    </div>
</body>
{% endblock content %}
</html>